### ISSUE TITLE
ProcessFailedException with no extra information when running via docker/podman

### ISSUE THREAD

**Issue by d-g-n** [scala-steward-org/scala-steward#3092] opened 2023-06-16 21:51 UTC
Hi, been having the following exception, will detail the setup below:

Running on MacOS Ventura 13.4, running latest podman with podman-desktop (also tried with docker and docker-desktop, same issue)

repos.md - just contains a well formed one liner entry of a private repo
git-ask-pass.sh - starts with a bash shebang, echos the env var at SCALA_STEWARD_PERSONAL_ACCESS_TOKEN out to stdout, appears to work
scala-steward.conf:
```

updates.fileExtensions = [".scala", ".sbt", ".sbt.shared", ".sc", ".yml", ".md", ".markdown", ".txt", ".properties"]

updatePullRequests = "always"

pullRequests.grouping = [
  { name = "all", "title" = "[SCALA STEWARD] Dependency updates", "filter" = [{"group" = "*"}] }
]
```

And this is the following command i'm running, relevant private details omitted, /opt/scala-steward/certs on my local filesystem contains appropriate certs for accessing a private artifactory, omitting the -D params for providing these does not change the error (newlines added for readability, all one line otherwise):
```
podman run 
-e SCALA_STEWARD_PERSONAL_ACCESS_TOKEN=omitted 
-v /Users/user/scala-steward/scala-steward:/opt/scala-steward 
-it docker.io/fthomas/scala-steward:latest-release 
-Djavax.net.ssl.trustStore=/opt/scala-steward/certs/jssecacerts 
-Djavax.net.ssl.trustStorePassword=omitted 
-Djavax.net.ssl.keyStoreType=PKCS12 
-Djavax.net.ssl.keyStore=/opt/scala-steward/certs/client.p12 
-Djavax.net.ssl.keyStorePassword=omitted 
--workspace /opt/scala-steward/workspace 
--process-timeout 30min 
--do-not-fork 
--repo-config /opt/scala-steward/config/scala-steward.conf 
--repos-file /opt/scala-steward/config/repos.md 
--git-author-email omitted 
--git-ask-pass /opt/scala-steward/config/git-ask-pass.sh 
--vcs-login omitted
```

And finally, the output is as follows:
```
2023-06-16 21:32:43,808 INFO   
  ____            _         ____  _                             _
 / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
 \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
  ___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
 |____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
 v0.24.0
 
2023-06-16 21:32:46,113 INFO  Loaded 128 artifact migration(s)
2023-06-16 21:32:46,476 INFO  Loaded 30 Scalafix migration(s)
2023-06-16 21:32:46,800 INFO  Loaded 2 repo config(s)
2023-06-16 21:32:47,430 INFO  Run self checks
2023-06-16 21:32:47,503 INFO  Using git version 2.40.1
2023-06-16 21:32:48,680 INFO  Using scalafix 0.11.0
2023-06-16 21:32:49,878 INFO  Using scalafmt 3.7.4
2023-06-16 21:32:50,817 INFO  Clean /opt/scala-steward/workspace/repos
2023-06-16 21:32:50,931 INFO  ──────────── Steward omitted ────────────
2023-06-16 21:32:50,938 INFO  Check cache of omitted
2023-06-16 21:32:52,386 INFO  Clone omitted
2023-06-16 21:33:03,036 INFO  Refresh cache of omitted
2023-06-16 21:33:05,544 INFO  Get dependencies in . from sbt
2023-06-16 21:33:50,951 ERROR Steward omitted failed
org.scalasteward.core.io.process$ProcessFailedException: 'sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 2.
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.6.2  (this may take some time)...
[info] [launcher] getting Scala 2.12.15 (for sbt)...

        at org.scalasteward.core.io.process$.$anonfun$slurp$7(process.scala:75)
        at org.scalasteward.core.io.process$.$anonfun$slurp$7$adapted(process.scala:69)
        at flatMap @ org.scalasteward.core.io.process$.$anonfun$slurp$5(process.scala:69)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at modify @ fs2.internal.Scope.close(Scope.scala:262)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
        at as @ org.scalasteward.core.io.process$.$anonfun$readLinesIntoBuffer$1(process.scala:123)
        at get @ fs2.internal.Scope.openScope(Scope.scala:275)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1214)
        at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
2023-06-16 21:33:50,994 INFO  ──────────── Total time: Steward omitted: 1m 60ms ────────────
2023-06-16 21:33:51,031 INFO  ──────────── Total time: run: 1m 3s 603ms ────────────

```

I've tried multiple different scala steward versions from 0.13.0, up to 0.24.0 with no difference in logic, i've tried to add `-DLOG_LEVEL=DEBUG` but will result in the same issue with no more details unfortunately, i can see that it will pull down the source and has access to the various certs and config files that are provided as a volume mount.

Would appreciate any and all advice, thank you.

**Comment by fthomas** [comment] 2023-06-17 20:02
@d-g-n This looks similar to #1814. sbt exits with code 2 and there is no output that hints what the problem is. Maybe you could use Scala Steward's `--env-var` command-line option to pass options to the sbt process for enabling remote debugging of sbt itself. Maybe something like `--env-var=JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5555` starts the sbt process that Scala Steward executes with remote debugging enabled.

**Comment by d-g-n** [comment] 2023-06-18 16:46
Thanks, i've been experimenting with a few different things,

I've been building local images and tweaking the source, i removed all extraneous sbt arguments until it was just running sbt compile against the downloaded project, unfortunately it would still crash after the scala stage

I don't think anything's wrong with my certs as i can bash into the container and run the bundled sbt bin against my repo using my certs and it works fine, however for whatever reason the very first time i run this command i get the following, manually accepting the prompt will allow it to work as expected:


```
9a2fdc9d558f:/opt/scala-steward/workspace/repos/removed# SBT_OPTS="-Djavax.net.ssl.keyStore=/opt/scala-steward/certs/client.p12 -Djavax.net.ssl.keyStorePassword=omitted -Djavax.net.ssl.keyStoreType=PKCS12 -Djavax.net.ssl.trustStorePassword=omitted -Djavax.net.ssl.trustStore=/opt/scala-steward/certs/jssecacerts" JAVA_OPTS="-Djavax.net.ssl.keyStore=/opt/scala-steward/certs/client.p12 -Djavax.net.ssl.keyStorePassword=omitted -Djavax.net.ssl.keyStoreType=PKCS12 -Djavax.net.ssl.trustStorePassword=omitted -Djavax.net.ssl.trustStore=/opt/scala-steward/certs/jssecacerts" /opt/docker/sbt/bin/sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.task.timings=true -Dsbt.supershell=false ;compile
sbt thinks that server is already booting because of this exception:
sbt.internal.ServerAlreadyBootingException: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [95] Not supported
	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:348)
	at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:294)
	at sbt.xMain$.getSocketOrExit(Main.scala:145)
	at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
	at sbt.xMain$.bootServerSocket$1(Main.scala:77)
	at sbt.xMain$.withStreams$1(Main.scala:85)
	at sbt.xMain$.run(Main.scala:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [95] Not supported
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.bind(UnixDomainServerSocket.java:140)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:114)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:93)
	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:342)
	... 23 more
Caused by: org.scalasbt.ipcsocket.NativeErrorException: [95] Not supported
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.bind(UnixDomainSocketLibrary.java:178)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.bind(UnixDomainServerSocket.java:136)
	... 26 more
Create a new server? y/n (default y)
y
[info] welcome to sbt 1.6.2 (Eclipse Adoptium Java 11.0.19)
[info] loading settings for project rms-tyga-build from plugins.sbt ...
[info] loading project definition from /opt/scala-steward/workspace/repos/removed/project
[info] compiling 1 Scala source to /opt/scala-steward/workspace/repos/removed/project/target/scala-2.12/sbt-1.0/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.15. Compiling...
```

I ended up at this issue: https://github.com/sbt/sbt/issues/6101, my project is using sbt 1.6.2, and even if i set the bundled sbt version in steward to match that, it still results in the same issues.

When running manually the only thing that i could do to get it to function was to add the following as suggested in the issue linked above to #sbt in SbtAlg:
```
          "--batch",
          "-Dsbt.server.forcestart=true",
```

After adding those lines it got past the quietly failing section without having to manually say yes to the prompt (which was likely the above exception just not bubbling up) as follows:
```
2023-06-18 16:35:41,127 INFO   
  ____            _         ____  _                             _
 / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
 \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
  ___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
 |____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
 v0.23.0-0-07063450-20230618-1728-SNAPSHOT
 
2023-06-18 16:35:43,474 INFO  Loaded 128 artifact migration(s)
2023-06-18 16:35:43,916 INFO  Loaded 30 Scalafix migration(s)
2023-06-18 16:35:44,244 INFO  Loaded 2 repo config(s)
2023-06-18 16:35:44,853 INFO  Run self checks
2023-06-18 16:35:44,896 WARN  
The workspace directory is empty: '/opt/scala-steward/workspace'
This is expected if this is your first Scala Steward run.
Make sure to preserve the workspace between runs for all features to work as expected.
https://github.com/scala-steward-org/scala-steward/blob/main/docs/faq.md#why-doesnt-self-hosted-scala-steward-close-obsolete-prs

2023-06-18 16:35:44,916 INFO  Using git version 2.40.1
2023-06-18 16:35:45,961 INFO  Using scalafix 0.11.0
2023-06-18 16:35:47,283 INFO  Using scalafmt 3.7.4
2023-06-18 16:35:48,219 INFO  Clean /opt/scala-steward/workspace/repos
2023-06-18 16:35:48,273 INFO  ──────────── Steward omitted ────────────
2023-06-18 16:35:48,279 INFO  Check cache of omitted
2023-06-18 16:35:49,578 INFO  Clone omitted
2023-06-18 16:35:58,920 INFO  Refresh cache of omitted
2023-06-18 16:36:01,173 INFO  Get dependencies in . from sbt
2023-06-18 16:39:23,836 INFO  Find updates for omitted
2023-06-18T16:40:27.220Z [WARNING] Your app's responsiveness to a new asynchronous 
event (such as a new connection, an upstream response, or a timer) was in excess
of 100 milliseconds. Your CPU is probably starving. Consider increasing the 
granularity of your delays or adding more cedes. This may also be a sign that you
are unintentionally running blocking I/O operations (such as File or InetAddress)
without the blocking combinator.
2023-06-18 16:40:50,575 INFO  Ignore com.typesafe.akka:(akka-actor, akka-actor_2.13) : 2.6.19 -> 2.6.20 -> 2.7.0-M1 -> ... -> 2.8.1-M1 -> 2.8.1 -> 2.8.2 (reason: ignored by config)
2023-06-18 16:40:50,579 INFO  Ignore com.typesafe.akka:(akka-http, akka-http_2.13) : 10.2.9 -> 10.2.10 -> 10.4.0-M1 -> ... -> 10.5.0 -> 10.5.1 -> 10.5.2 (reason: ignored by config)
2023-06-18 16:40:50,581 INFO  Ignore com.typesafe.akka:(akka-http-testkit, akka-http-testkit_2.13) : 10.2.9 -> 10.2.10 -> 10.4.0-M1 -> ... -> 10.5.0 -> 10.5.1 -> 10.5.2 (reason: ignored by config)
2023-06-18 16:40:50,583 INFO  Ignore com.typesafe.akka:(akka-slf4j, akka-slf4j_2.13) : 2.6.19 -> 2.6.20 -> 2.7.0-M1 -> ... -> 2.8.1-M1 -> 2.8.1 -> 2.8.2 (reason: ignored by config)
2023-06-18 16:40:50,585 INFO  Ignore com.typesafe.akka:(akka-stream, akka-stream_2.13) : 2.6.19 -> 2.6.20 -> 2.7.0-M1 -> ... -> 2.8.1-M1 -> 2.8.1 -> 2.8.2 (reason: ignored by config)
2023-06-18 16:40:50,586 INFO  Ignore com.typesafe.akka:(akka-testkit, akka-testkit_2.13) : 2.6.19 -> 2.6.20 -> 2.7.0-M1 -> ... -> 2.8.1-M1 -> 2.8.1 -> 2.8.2 (reason: ignored by config)
2023-06-18 16:40:50,589 INFO  Ignore de.heikoseeberger:(akka-http-json4s, akka-http-json4s_2.13) : 1.39.2 -> 1.40.0-RC1 -> 1.40.0-RC2 -> 1.40.0-RC3 (reason: no suitable next version)
2023-06-18 16:40:50,598 INFO  Ignore org.json4s:(json4s-ext, json4s-ext_2.13) : 4.0.6 -> 4.1.0-M1 -> 4.1.0-M2 -> 4.1.0-M3 (reason: no suitable next version)
2023-06-18 16:40:50,600 INFO  Ignore org.json4s:(json4s-jackson, json4s-jackson_2.13) : 4.0.6 -> 4.1.0-M1 -> 4.1.0-M2 -> 4.1.0-M3 (reason: no suitable next version)
2023-06-18 16:40:50,992 INFO  Found 16 updates:
  omitted:(omitted, omitted_2.13) : 3.6.0 -> 3.10.0
  omitted:(omitted, omitted_2.13) : 5.0.7 -> 5.0.12
  omitted:omitted : 2.1.0 -> 2.1.7
  omitted:(omitted, omitted_2.13) : 5.2.2 -> 5.2.7
  ch.qos.logback:logback-classic : 1.2.11 -> 1.2.12
  com.github.tomakehurst:wiremock : 2.32.0 -> 2.33.2
  com.timushev.sbt:sbt-updates : 0.6.3 -> 0.6.4
  io.kamon:sbt-kanela-runner : 2.0.13 -> 2.0.14
  joda-time:joda-time : 2.10.14 -> 2.12.5
  net.vonbuchholtz:sbt-dependency-check : 4.2.0 -> 4.3.0
  org.joda:joda-convert : 2.2.2 -> 2.2.3
  org.scala-lang:scala-library : 2.13.10 -> 2.13.11
  org.scala-sbt:sbt : 1.6.2 -> 1.9.0
  org.scoverage:sbt-scoverage : 1.9.3 -> 2.0.8
  org.specs2:(specs2-core, specs2-core_2.13) : 4.16.0 -> 4.16.1
  org.specs2:(specs2-mock, specs2-mock_2.13) : 4.16.0 -> 4.16.1
2023-06-18 16:40:51,031 INFO  omitted is outdated:
  new version: omitted : 3.6.0 -> 3.10.0
  new version: omitted : 5.0.7 -> 5.0.12
  new version: omitted : 5.2.2 -> 5.2.7
  new version: omitted : 2.1.0 -> 2.1.7
  new version: ch.qos.logback:logback-classic : 1.2.11 -> 1.2.12
  new version: com.github.tomakehurst:wiremock : 2.32.0 -> 2.33.2
  new version: com.timushev.sbt:sbt-updates : 0.6.3 -> 0.6.4
  new version: io.kamon:sbt-kanela-runner : 2.0.13 -> 2.0.14
  new version: joda-time:joda-time : 2.10.14 -> 2.12.5
  new version: net.vonbuchholtz:sbt-dependency-check : 4.2.0 -> 4.3.0
  new version: org.joda:joda-convert : 2.2.2 -> 2.2.3
  new version: org.scala-lang:scala-library : 2.13.10 -> 2.13.11
  new version: org.scala-sbt:sbt : 1.6.2 -> 1.9.0
  new version: org.scoverage:sbt-scoverage : 1.9.3 -> 2.0.8
  new version: org.specs2:(specs2-core, specs2-core_2.13) : 4.16.0 -> 4.16.1
  new version: org.specs2:(specs2-mock, specs2-mock_2.13) : 4.16.0 -> 4.16.1
2023-06-18 16:40:51,051 INFO  Nurture omitted
2023-06-18 16:40:51,079 INFO  Found 1 update:
  all (group) {
    omitted : 3.6.0 -> 3.10.0
    omitted : 5.0.7 -> 5.0.12
    omitted : 2.1.0 -> 2.1.7
    omitted : 5.2.2 -> 5.2.7
    ch.qos.logback:logback-classic : 1.2.11 -> 1.2.12
    com.github.tomakehurst:wiremock : 2.32.0 -> 2.33.2
    com.timushev.sbt:sbt-updates : 0.6.3 -> 0.6.4
    io.kamon:sbt-kanela-runner : 2.0.13 -> 2.0.14
    joda-time:joda-time : 2.10.14 -> 2.12.5
    net.vonbuchholtz:sbt-dependency-check : 4.2.0 -> 4.3.0
    org.joda:joda-convert : 2.2.2 -> 2.2.3
    org.scala-lang:scala-library : 2.13.10 -> 2.13.11
    org.scala-sbt:sbt : 1.6.2 -> 1.9.0
    org.scoverage:sbt-scoverage : 1.9.3 -> 2.0.8
    org.specs2:(specs2-core, specs2-core_2.13) : 4.16.0 -> 4.16.1
    org.specs2:(specs2-mock, specs2-mock_2.13) : 4.16.0 -> 4.16.1
  }
2023-06-18 16:40:51,216 INFO  Process update all
2023-06-18 16:40:51,968 INFO  Found PR https://github.com/omitted/pull/152
2023-06-18 16:40:54,026 INFO  PR update strategy is set to always
2023-06-18 16:40:54,029 INFO  Merge branch main into update/all and apply again
2023-06-18 16:43:43,799 WARN  Unable to bump version for update org.specs2:(specs2-mock, specs2-mock_2.13) : 4.16.0 -> 4.16.1
2023-06-18 16:43:43,803 INFO  Push 16 commit(s)
2023-06-18 16:43:59,065 INFO  ──────────── Total time: Steward omitted: 8m 10s 790ms ────────────
2023-06-18 16:43:59,074 INFO  ──────────── Total time: run: 8m 14s 222ms ────────────

```

And it eventually appears to succeed, the above run is with a clean workspace.

I don't know the full ramifications of adding those lines to the code in general, would you be opposed to a PR containing those new flags when running sbt?

**Comment by fthomas** [comment] 2023-06-19 06:30
Great find @d-g-n!

> would you be opposed to a PR containing those new flags when running sbt?

I don't see any downsides in adding those flags. Maybe it would be even better if we instruct sbt to not start the server at all instead of force starting it since Scala Steward doesn't need any server capabilities. Could you check if running sbt with [`-Dsbt.server.autostart=false`](https://stackoverflow.com/questions/48591179/can-one-disable-the-sbt-1-x-server) or [`--no-server`](https://github.com/sbt/sbt/blob/v1.6.2/sbt#L634) also fixes your problem?

**Comment by fthomas** [comment] 2023-06-19 07:26
Just remembered #1705 (which removed `-batch`) and #1712 (which emulated `-batch` by closing stdin). I would therefore prefer to fix this without adding `-batch` again.

**Comment by d-g-n** [comment] 2023-06-19 09:09
Hey, i tried to run it with --no-server but got the same issue:

```
�org.scalasteward.core.io.process$ProcessFailedException: 'SBT_OPTS=-Djavax.net.ssl.keyStore=/opt/scala-steward/certs/client.p12 -Djavax.net.ssl.keyStorePassword=-Djavax.net.ssl.keyStoreType=PKCS12 -Djavax.net.ssl.trustStorePassword=-Djavax.net.ssl.trustStore=/opt/scala-steward/certs/jssecacerts sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false --no-server ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 2.
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.6.2  (this may take some time)...
[info] [launcher] getting Scala 2.12.15 (for sbt)...

        at org.scalasteward.core.io.process$.$anonfun$slurp$7(process.scala:75)
        at org.scalasteward.core.io.process$.$anonfun$slurp$7$adapted(process.scala:69)
        at flatMap @ org.scalasteward.core.io.process$.$anonfun$slurp$5(process.scala:69)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at modify @ fs2.internal.Scope.close(Scope.scala:262)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
        at as @ org.scalasteward.core.io.process$.$anonfun$readLinesIntoBuffer$1(process.scala:123)
        at get @ fs2.internal.Scope.openScope(Scope.scala:281)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1214)
        at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
�2023-06-19 08:32:24,142 INFO  ──────────── Total time: Steward omitted: 1m 5s 585ms ────────────
�2023-06-19 08:32:24,154 INFO  ──────────── Total time: run: 1m 14s 831ms ────────────
```

However, just running it with `"-Dsbt.server.forcestart=true"` but without `-batch` does allow it to work

**Comment by fthomas** [comment] 2023-06-19 13:18
Ok, then let's add `-Dsbt.server.forcestart=true`.

**Closed** 2023-06-19 18:01 UTC
