### ISSUE TITLE
Spurious cats-effect update when updating cats

### ISSUE THREAD

**Issue by bplommer** [scala-steward-org/scala-steward#1928] opened 2021-02-11 15:53 UTC
This scala-steward PR is for updating `cats-kernel-laws` and `cats-laws` to v2.4.1 - however it also changes the `catsEffectVersion` val, which is used (only) for `cats-effect-laws`.

https://github.com/fd4s/fs2-kafka/pull/519

**Comment by fthomas** [comment] 2021-02-11 17:04
Duplicate of #1184.

**Closed by fthomas** 2021-02-11 17:04 UTC
