### ISSUE TITLE
Formatting on the version upgrading

### ISSUE THREAD

**Issue by danicheg** [scala-steward-org/scala-steward#2245] opened 2021-09-22 19:39 UTC
This is likely a feature request issue rather than a bug.
It'd be great if Steward will run `scalafmtSbt` on the version upgrading. On artefact migration, it's possible to violate format rules. And that might lead to failed CI for Steward's PR. Just like it was here: https://github.com/typelevel/keypool/pull/255/files#diff-8fd74420ca55aa91d4c53775d2a55a999c405b5a4fafeaf73b7f0ef83e1f3b0cR7

**Comment by fthomas** [comment] 2021-09-22 19:44
Looks like a duplicate of #1889 to me.

**Closed** 2021-10-08 05:57 UTC
Labels: duplicate
