### ISSUE TITLE
Error when changes affect yarn.lock: Your local changes to the following files would be overwritten by checkout

### ISSUE THREAD

**Issue by AlexITC** [scala-steward-org/scala-steward#2416] opened 2021-12-20 15:35 UTC
It seems that the steward needs to consider the `yarn.lock` file which is usually tracked by scala.js projects, I got the steward installed for a private repository, which is based in a [template involving scala.js](https://github.com/wiringbits/scala-webapp-template) which should got some updates but failed.

While looking at the logs, I found an error log that indicates a problem when the `yarn.lock` file is updated but the steward didn't committed/removed it before switching to a new branch.

```
  2021-12-19 03:08:20,010 INFO  The-Org/the-app is outdated:
    PR outdated: com.alexitc:(sjs-material-ui-facade, sjs-material-ui-facade_sjs1_2.13) : 0.1.4 -> 0.1.5 (https://github.com/The-Org/the-app/pull/55)
    PR outdated: org.scalameta:(scalafmt-core, scalafmt-core_2.13) : 2.7.5 -> 3.2.1 (https://github.com/The-Org/the-app/pull/67)
    new version: com.fasterxml.jackson.module:(jackson-module-scala, jackson-module-scala_2.13) : 2.12.6 -> 2.13.0
    new version: org.web3j:core : 4.8.9 -> 5.0.0
  2021-12-19 03:08:20,012 INFO  Nurture The-Org/the-app
  2021-12-19 03:08:20,019 INFO  Found 4 updates:
    com.alexitc:(sjs-material-ui-facade, sjs-material-ui-facade_sjs1_2.13) : 0.1.4 -> 0.1.5
    com.fasterxml.jackson.module:(jackson-module-scala, jackson-module-scala_2.13) : 2.12.6 -> 2.13.0
    org.scalameta:(scalafmt-core, scalafmt-core_2.13) : 2.7.5 -> 3.2.1
    org.web3j:core : 4.8.9 -> 5.0.0
  2021-12-19 03:08:20,028 INFO  Process update com.alexitc:(sjs-material-ui-facade, sjs-material-ui-facade_sjs1_2.13) : 0.1.4 -> 0.1.5
  2021-12-19 03:08:20,213 INFO  Found PR https://github.com/The-Org/the-app/pull/55
  2021-12-19 03:08:22,120 ERROR Steward The-Org/the-app failed
  java.io.IOException: 'GIT_ASKPASS=/home/runner/scala-steward/askpass.sh "SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" git -c core.hooksPath=/dev/null checkout update/sjs-material-ui-facade-0.1.5' exited with code 1
  error: Your local changes to the following files would be overwritten by checkout:
  	lib/ui/yarn.lock
  Please commit your changes or stash them before you switch branches.
  Aborting
  
  	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:57)
  	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:53)
  	at blocking @ org.scalasteward.core.io.process$.$anonfun$slurp$7(process.scala:53)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  	at modify @ fs2.internal.Scope.close(Scope.scala:262)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:156)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1153)
  	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
  2021-12-19 03:08:22,124 INFO  ──────────── Total time: Steward The-Org/the-app: 5m 25s 58ms ────────────```

**Comment by fthomas** [comment] 2021-12-21 13:39
It should have been committed if it was updated because of a version bump since Scala Steward commits all changed files. Does the build makes changes to `yarn.lock`? We currently do not discard changes after executing the build (but probably should) and I could imagine that this is the cause for the error.

**Comment by AlexITC** [comment] 2021-12-21 14:30
> Does the build makes changes to yarn.lock?

Usually, it doesn't but from time to time `yarn.lock` seems to get updated unnecessarily.

> We currently do not discard changes after executing the build (but probably should) and I could imagine that this is the cause for the error.

I believe this will likely fix the problem, what I'd find weird is that a non-scala.js PR gets updated the `yarn.lock` but that wouldn't be scala-steward's fault.

**Closed** 2022-01-12 14:30 UTC
