### ISSUE TITLE
Dependencies with hash no longer updated

### ISSUE THREAD

**Issue by terryhendrix1990** [scala-steward-org/scala-steward#1790] opened 2020-12-07 17:20 UTC
Some of our libraries are not being updated anymore starting version 0.7.0 and up. The last working version seems to be 0.6.0.

We have a hash in our release versions. Template: `x.y.z-yyyyMMdd-HHmmss-<git hash>`

example: 
`1.0.0-20201119-091040-d8b7496c`

**Comment by fthomas** [comment] 2020-12-07 19:06
This has been caused by https://github.com/scala-steward-org/scala-steward/pull/1549.

**Comment by terryhendrix1990** [comment] 2020-12-08 12:45
Is there a way to use 0.8.1 and still have these versions detected? I've tried using `version = { prefix = "1.0.0" }` but it does not work.

**Comment by fthomas** [comment] 2020-12-08 15:12
No, we need to tweak `Version.selectNext` to allow such updates again.

**Comment by mzuehlke** [comment] 2020-12-09 08:31
This most likely got fixed by #1794

**Comment by fthomas** [comment] 2020-12-09 15:38
#1794 was necessary but not sufficient. #1798 should fix it completely.

**Closed** 2020-12-09 16:57 UTC
