### ISSUE TITLE
Consider updating .git-blame-ignore-revs when committing scalafmt changes

### ISSUE THREAD

**Issue by nafg** [scala-steward-org/scala-steward#2603] opened 2022-05-15 19:01 UTC
See https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by mzuehlke** [comment] 2022-05-18 10:43
Duplicate of #2567

**Closed by mzuehlke** 2022-05-18 10:43 UTC
