### ISSUE TITLE
Support for updating multiple branches

### ISSUE THREAD

**Issue by djspiewak** [scala-steward-org/scala-steward#1759] opened 2020-11-22 17:32 UTC
Cats Effect is a good exemplar here, but there are now several projects with multiple concurrent active branches right now, both due to Cats Effect 3 and Scala 3. At present, only Cats Effect `series/2.x` (the primary branch) is being managed by scala-steward, while it would be nice if `series/3.x` were *also* thus managed. As far as I can tell, there is no way to configure this at present.

**Comment by fthomas** [comment] 2020-11-27 08:09
I'm closing this since it is a duplicate of #20 for which there is a PR at #1469.

**Closed by fthomas** 2020-11-27 08:09 UTC
