### ISSUE TITLE
Using scala-steward to update scalaVersion ?

### ISSUE THREAD

**Issue by smarter** [scala-steward-org/scala-steward#589] opened 2019-06-18 09:21 UTC
Would it be possible to adapt scala-steward to update not only library dependencies but the version of Scala used to ? This would make sense between minor releases of scalac (e.g. 2.12.7 -> 2.12.8) but I'd be particularly interested in automating upgrades between Dotty releases (right now we manually bump a bunch of projects when we do a release, but that doesn't scale).

**Comment by fthomas** [comment] 2019-06-18 12:06
I disabled Scala updates early in the development of scala-steward because it produced some bad PRs and it is harder to get Scala updates right compared to normal dependencies and plugins. But maybe we should revise that position now that we have a better internal architecture for dealing with updates. Do you have an example project where you'd like scala-steward to update the Dotty version and maybe an example PR how such update looks like?

**Comment by smarter** [comment] 2019-06-18 12:20
> Do you have an example project where you'd like scala-steward to update the Dotty versio

For example: https://github.com/scala/scala-xml

> maybe an example PR how such update looks like?

I don't have a good example but ideally the procedure should be:
- If `scalaVersion` starts with `0.` update it to the latest dotty release
- If `crossScalaVersion` has one or more version that starts with `0.`, update the greatest one to the latest dotty release.

Getting the version number for the latest dotty release from maven is non-trivial since our artifacts are cross-built, e.g. the latest release is https://repo1.maven.org/maven2/ch/epfl/lamp/dotty_0.16/0.16.0-RC3/, but the next one will be dotty_0.17/0.17.0-RC1.

Additionally, an upgrade of dotty should be coupled with an upgrade of sbt-dotty to the latest release, e.g. 0.3.3 currently: https://repo1.maven.org/maven2/ch/epfl/lamp/sbt-dotty_2.12_1.0/0.3.3/

**Comment by SethTisue** [comment] 2019-06-20 07:35
often both `build.sbt` and `.travis.yml` need updating

perhaps in situations like this where Scala Steward cannot have high confidence that it is able to update all the locations that might matter, it could issue some kind of warning saying manual intervention is likely to be needed?

**Comment by fthomas** [comment] 2019-06-20 14:10
@smarter Thanks for the procedure, I'll see if we can support Dotty updates.

@SethTisue That are good suggestion, thanks. Maybe a config option for preventing (or enabling) low-confidence PRs could be useful too.

**Comment by hugo-vrijswijk** [comment] 2019-06-24 18:37
Adding to this, with the Scalafix integrations it'd be super cool if Scala Steward could also run those for minor version updates (e.g. 2.12 -> 2.13)

**Comment by SethTisue** [comment] 2019-07-09 21:07
duplicate of #145?

**Comment by anilkumarmyla** [comment] 2020-04-01 02:49
To summarize, there are multiple ideas that are being discussed in this

1. Upgrade Scala 2.x compilers
2. travis.yaml (OR configuration files for scala builds) updates 
3. Upgrade Dotty with plugin
4. Scalafix integrations between major version upgrades
5. Low-confidence or draft PRs

1. has experimental support with repo config (`updates.includeScala=true`) with #1381 
2. might have support (with 1) but not validated yet
3. I do not have enough context to comment on this
4. can be supported with added scalafix rules for scala upgrades
5. is something that can implemented

**Comment by SethTisue** [comment] 2020-09-08 15:46
> it is harder to get Scala updates right compared to normal dependencies and plugins

a further thought on this: much of Scala Steward's value is simply in notifying repo owners that there is a new version

and not just notifying, but there is further real value in actually placing the upgrade as a concrete todo item in the maintainer's queue

of course there is also extra bonus value at the end if the PR submitted is actually a working PR!

 but really, a lot of the value comes before that. something to think about

**Comment by SethTisue** [comment] 2020-09-08 15:51
> heck, it could even use GitHub's new "draft PR" feature

the feature is no longer new but is now well established and widely used, and I still think it's an appropriate solution here

**Closed** 2021-02-26 19:15 UTC
Labels: enhancement
