### ISSUE TITLE
StackOverflowError when applying migrations for http4s

### ISSUE THREAD

**Issue by tkawachi** [scala-steward-org/scala-steward#850] opened 2019-08-19 02:07 UTC
I encountered StackOverflowError when applying migrations for http4s. I set `--env-var "SBT_OPTS=-XX:MaxMetaspaceSize=1g -Xss8m"` so that the stack size is enough large.

Following is the part of the log.

```
2019-08-17 11:23:13,380 INFO  Process update org.http4s:http4s-blaze-client : 0.10.1 -> 0.20.10
2019-08-17 11:23:13,411 INFO  Applying migrations: NonEmptyList(Migration(org.http4s,NonEmptyList(http4s-.*),Version(0.20.0),NonEmptyList(github:http4s/http4s/v0_20?sha=v0.20.10),None))
(snip)
java.lang.StackOverflowError
	at java.io.UnixFileSystem.getLastModifiedTime(Native Method)
	at java.io.File.lastModified(File.java:943)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at scala.meta.internal.classpath.ClasspathIndex$Builder.scala$meta$internal$classpath$ClasspathIndex$Builder$$expandJarEntry(ClasspathIndex.scala:135)
	at scala.meta.internal.classpath.ClasspathIndex$Builder.expandEntry(ClasspathIndex.scala:101)
	at scala.meta.internal.classpath.ClasspathIndex$Builder.$anonfun$expandJarEntry$1(ClasspathIndex.scala:156)
	at scala.meta.internal.classpath.ClasspathIndex$Builder.$anonfun$expandJarEntry$1$adapted(ClasspathIndex.scala:153)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.meta.internal.classpath.ClasspathIndex$Builder.scala$meta$internal$classpath$ClasspathIndex$Builder$$expandJarEntry(ClasspathIndex.scala:153)
(Same lines repeat here)
	at scala.meta.internal.classpath.ClasspathIndex$Builder.scala$meta$internal$classpath$ClasspathIndex$Builder$$expandJarEntry(ClasspathIndex.scala:153)
	at scala.meta.internal.classpath.ClasspathIndex$Builder.expandEntry(ClasspathIndex.scala:101)
	at scala.meta.internal.classpath.ClasspathIndex$Builder.$anonfun$expandJarEntry$1(ClasspathIndex.scala:156)
[error] (foo/compile:scalafix) java.lang.StackOverflowError
[error] (bar/compile:scalafix) java.lang.StackOverflowError
[error] Total time: 171 s, completed Aug 17, 2019 11:27:55 AM
```

**Comment by tkawachi** [comment] 2019-08-19 09:40
Is there option to turn off scalafix migrations? It would be a workaround for us.

**Comment by fthomas** [comment] 2019-08-20 13:05
No, there is no option to turn off Scalafix migrations. The stack trace hints at a problem with scalameta. I guess it could be reproduced without Scala Steward.

**Comment by fthomas** [comment] 2020-09-03 10:59
I'm going to close this because

* since https://github.com/scala-steward-org/scala-steward/pull/1057 Scalafix migrations can be disabled by passing an external Scalafix migrations file via `--scalafix-migrations` that just contains `disableDefaults = false`.
* since https://github.com/scala-steward-org/scala-steward/pull/1124 failing Scalafix migrations do not crash the update process. So Scala Steward will update the dependency even if the Scalafix migration failed.

Both changes should  be helpful in case of failing Scalafix migrations.

**Closed by fthomas** 2020-09-03 10:59 UTC
